### ISSUE TITLE
traceback error after attempting chmod +x executable 

### ISSUE THREAD

**Issue by JuFisch** [LearnProgramming/learntris#46]
```
Couldn't run './learntris.py' due to a permission error.
Make sure your program is marked as an executable.
localhost:learntris Julie1_macbook_pro$ chmod +x learntris.py
localhost:learntris Julie1_macbook_pro$ ./testris.py ./learntris.py
--------------------------------------------------
Traceback (most recent call last):
  File "./testris.py", line 165, in main
    run_tests(cmdline, use_shell)
  File "./testris.py", line 131, in run_tests
    program = spawn(program_args, use_shell)
  File "./testris.py", line 81, in spawn
    stdout=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
--------------------------------------------------
Oh no! Testris encountered an unexpected problem while
attempting to run your program. Please report the above
traceback in the issue tracker, so that we can help you
with the problem and provide a better error message in
the future.
```

**Comment by raylu** [comment]
Your file is executable but your OS doesn't know how to run that executable. You should get an error (though a different one) if you try to run just `./learntris.py`. The problem is almost certainly that you need to add a [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) to the start of the file:

    #!/usr/bin/env python
